[[navbar]]
  identifier = "home"
  name = "Home"
  url = "../"
  weight = 1
[[navbar]]
  identifier = "list"
  name = "Positions"
  url = "/positions/"
  weight = 2
[[navbar]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 3
